### ISSUE TITLE
Error after "info  Crunching the gif animation"

### ISSUE THREAD

**Issue by iam-medvedev** [IonicaBizau/gif-cli#13]
Cant run `gif file.gif`

```
info  Crunching the gif animation.
(node:35408) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
events.js:161
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at exports._errnoException (util.js:1023:11)
    at WriteWrap.afterWrite [as oncomplete] (net.js:804:14)
```

**Comment by jeffskafi** [comment]
having the same error

**Comment by cakekindel** [comment]
Here's how I solved this - a dependency of a dependency of `gif-cli` doesn't work for Node >=6.0.0 so you have to download the v5.9.1 dist from [Node's dist archive](https://nodejs.org/dist/v5.9.1/win-x64/). I saved mine as `node5.exe` in Downloads.

Use your global installation of node to install and build `gif-cli` (by this i just mean running `npm i -g gif-cli`), then you can run it using 

```
%HOMEPATH%\Downloads\node5.exe %APPDATA%\npm\node_modules\gif-cli\bin\gif-cli path-to-gif.gif
```

To improve my own quality of life I also edited `gif.cmd` and `gif-cli.cmd` in `%APPDATA%\npm\` to just this script:
```
%HOMEPATH%\Downloads\node5.exe %APPDATA%\npm\node_modules\gif-cli\bin\gif-cli %*
```

This way you can run `gif image.gif` or `gif-cli image.gif` in any cmd and any directory rather than the long thing above.
